[package]
name = "bbl-oiio-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bbl-build = {git = "https://github.com/anderslanglands/bbl-build-rs.git", rev="fd2a2d1"}

